server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/cs544?useSSL=false&serverTimezone=America/Chicago
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create-drop
logging:
  level:
    root: WARN