server:
  port: 8081
spring:
  application:
    name: vehicle
  datasource:
    url: jdbc:mysql://localhost/cs544?useSSL=false&serverTimezone=America/Chicago
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    password: '@Aselastar21'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create-drop

logging:
  level:
    root: WARN