
server:
  port: 8082

spring:
  application:
    name: schedule
  datasource:
    username: root
    url: jdbc:mysql://localhost/cs544?useSSL=false&serverTimezone=America/Chicago
    password: aungkhant
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create-drop
logging:
  level:
    root: WARN
