
server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: driver
  datasource:
    url: jdbc:mysql://localhost/cs544?useSSL=false&serverTimezone=America/Chicago
    username: root
    password: aungkhant
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create-drop
logging:
  level:
    root: WARN

